### ISSUE TITLE
windows arm

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabctools#63]
Recently I had someone join discord and ask if sab is supported on windows arm...

> Windows 10 enables existing unmodified x86 apps to run on Arm devices. 
> Windows 11 adds the ability to run unmodified x64 Windows apps on Arm devices!

> Arm64EC (“Emulation Compatible”) enables you to incrementally build new apps, or port existing apps, to take advantage of native Arm performance where possible, while utilizing existing x64 code & libraries until fully migrated.
-- https://www.neowin.net/news/arm64ec-now-fully-supports-windows-11-on-arm/

Which brought up an interesting question what is supported, even usable with emulation?
What is lacking to get it to run natively? 

sab core:
- python //  they do arm64 builds with 3.11+ -- https://bugs.python.org/issue33125
  - 3.11rc1 - https://www.python.org/ftp/python/3.11.0/python-3.11.0rc1-arm64.exe
- sabyenc // ???
- installer (nsis) // ???

utilities:
- rar // no win arm release.
- 7zip // has arm64 exe
- multipar // no win arm (asked: https://github.com/Yutaka-Sawada/MultiPar/issues/73 )

I'm getting a free arm based windows 11 machine here in a month (samsung galaxy book go - snapdragon 7c gen2  w/4g ram). 
I'm sure its going to be awful but hey something to test on.

**Comment by animetosho** [comment]
I've tested node-yencode on ARM/ARM64 Windows and have had it working, so it should be possible to get sabyenc to work.

A key problem is that I don't know how Python handles cross-compilation, particularly getting the target arch in setuptools. There's no ARM version of Visual Studio, meaning that you can only get Windows ARM binaries through cross-compilation.  
If the cross-compilation issue can be addressed, I don't see any major blockers for Windows ARM compatibility in sabyenc.

RAR only has an ARM build for macOS. I've never seen any non-x86 support for other platforms, so one wonders if it's just a lack of interest for now. Considering the lack of Linux ARM support, I wouldn't hold my breath for Windows ARM.

par2j has a fair number of assumed x86-isms, however I'd imagine it's mostly just the GF16 and hashing routines. The source code is available though, so someone interested enough could patch those out to make it work (unlike RAR). However, unless ARM specific optimisations are added, it probably won't have much of a perf advantage over par2cmdline.

**Comment by sanderjo** [comment]
> RAR only has an ARM build for macOS. I've never seen any non-x86 support for other platforms, so one wonders if it's just a lack of interest for now. **Considering the lack of Linux ARM support**, I wouldn't hold my breath for Windows ARM.

Maybe I don't understand, but:
* for SAB, we need unrar (CLI only), so not the winrar gui stuff.
* on Linux, compiling unrar on ARM (and RISCV) is super easy: download unrar source, untar, make ... done

**Comment by animetosho** [comment]
My bad - "rar" was mentioned, so I assumed that instead of unrar.

I just tried and the UnRAR source code seems to compile for Windows ARM/64 without issue.

> The makefile of unrar contains a part CYGWIN using GCC. So I guess that is for compiling on WIndows?

I don't think Cygwin/MSYS support Windows ARM/64, but there's UnRAR.vcxproj. Just open that in Visual Studio, add ARM/64 as a target architecture, change the platform/SDK toolset and compile.

**Comment by Safihre** [comment]
I worry more about python modules not in our control that need compiling, like cffi and of course cryptography with its Rust components..

**Comment by thezoggy** [comment]
Got my win11 arm laptop. Took half a day for it to finish installing updates 🤣

Will play around and report back

**Comment by sanderjo** [comment]
@thezoggy any update on your Windows on ARM? Does it run SABnzbd?

FWIW:
It seems github actions now do Windows on ARM: https://github.blog/changelog/2022-09-28-github-actions-self-hosted-runners-now-support-windows-arm-hardware/
pyinstaller: "Support building native ARM applications for Windows. If PyInstaller is ran on an ARM machine with an ARM build of Python, it will prodice an ARM application."

Reason I'm asking: In a shop in Germany, I saw a SAMSUNG Galaxy Book Go LTE: Windows 11 Home on Qualcomm Snapdragon 700

**Comment by Safihre** [comment]
@thezoggy did you ever test this?

**Comment by Safihre** [comment]
We can build using `cibuildwheels` to cross-compile, but currently it's not really detecting AMR64 well so I think the wheels produced are not optimal if they work at all.
https://github.com/sabnzbd/sabctools/actions/runs/6169465179/job/16743882013
But also doubt if it's worth investigating since nobody has asked for it since this issue was openend 1 year ago 😊

**Comment by thezoggy** [comment]
No idea how this got overlooked. I did play around with sab and arm but there are a few hiccups. Python arm installs fine but not all our depdencies would install in it. If I moved to x64 python then it worked. But then fallout is that in our detection python says it's x64 not arm. That then lead me down the path of getting our utilities working in arm better.. which eventually resulted in par2cmdline-turbo. I never really ran sab itself fully in the arm env because of limited space/resources but it worked enough piece meal. 

At some point we probably should add proper arm detection for windows but wasn't enough for me to justify bloating our repo with binaries for our utilities at this time. (Plus the whole bad detection depending on which python your using)

**Comment by sanderjo** [comment]
FWIW:
I installed Windows 11 (64bit) on Raspi 4 (ARM, 8GB RAM), and that works (impressive) ... although a bit slow.

I then installed SABnzbd for Windows, so for x86_64. So that gets emulated on Windows 11 on ARM. 
Result: It all works. 
10GB test download: Download speed is 20 MB/s. Not bad!

So: 
* I would say about sabctools / sabnzbd native for Windows on ARM: nice to have, but no urgent need now ... let's wait until there is pull.
* with the Raspi 4 (and probably Raspi 5) it is feasible to do Windows-on-ARM development/compiling/etc. 

![image](https://github.com/sabnzbd/sabctools/assets/1273502/b7ccbf90-1b0c-44eb-ad18-adc57cc9f9ec)


![image](https://github.com/sabnzbd/sabctools/assets/1273502/fae64b33-54bb-463d-9520-ab2bc6213d8c)
