### ISSUE TITLE
Incorrect CRC32 failure

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabctools#96]
@animetosho @mnightingale sorry to bother you again for help, but I am not sure how to fix this.

A user reported SABnzbd failing an NZB due to article CRC errors, while another downloader succeeded.
When I disable the article CRC32 handling in SABnzbd, indeed the download succeeds and verifies using par2, so `sabctools` seems wrong.
I _think_ it has to do with the formatting of the CRC32:
```
=yend size=409600 part=1 pcrc32=ffffffff79b5066a
```
If I use the Python verification of the decoded content it produces `79b5066a`, so it matches, minus the `ffffffff`.

I added a test-case in this branch:
https://github.com/sabnzbd/sabctools/commit/a2eddde4c19f7dcde1c36439820d4f9a94d8b565

How do we handle that in `sabctools`?

**Comment by animetosho** [comment]
`ffffffff79b5066a` isn't a valid CRC32, so failing seems sensible to me.

It's not obvious to me how that CRC32 was produced.  
Given that the value is a 64-bit number, a thought could be that the client mistakenly sign-extended the CRC32 to 64-bit, and serialised it as such. However, it doesn't quite seem right, given the first hex digit (7) is < 8.  

CRC32 does require a bit flip at the end; perhaps the client computed the CRC32 correctly, but performed the bit flip as a 64-bit integer, without truncating back to 32-bit.

	crc: int64 = ~0                  # initial CRC
	crc = compute_crc32(crc, data)  # computes valid CRC32
	crc = ~crc                      # final bit flip; not correctly truncated to 32 bit because this is an int64 type

If you really do want to make this work, truncating to the last 8 hex digits seems to be the most sensible (and padding the left with 0s if <8 digits), though when you're dealing with invalid values, it's anyone's guess what is correct.

**Comment by mnightingale** [comment]
Can you do a head request and see if it identifies the poster tool?

I agree with the above and I'd guess it should be made to work because the posts are out there now and will probably continue to be posted in this broken way.

To start with I'd find the end of crc32=  and do something like https://gist.github.com/mnightingale/5628136d1016d47ae405b52c684d86cb to take the last 8 characters.

I needed to define YENC_SP (space = 0x20) to allow the new and I think another test to pass, I'm not sure if the original had a space at the end but I think it's worth allowing anyway.

I was confused with another broken test, test_crc_pickles and test_small_file_pickles should probably glob `crc_*.pickle` etc. it is picking up your new .yenc file.

We could add support for < 8 characters but that seems unlikely compared to recieving exactly 8 or 16, bit yEnc specification is quite unspecific about what the expect.

**Comment by animetosho** [comment]
> the yEnc specification is quite unspecific about what to expect

In general, the specification is rather horrible. It doesn't even clarify that the CRC32 should be hex encoded; one could guess the intention from the examples provided, but a good specification would clarify without making one guess like this.  
It also doesn't specify which CRC32 polynomial to use, though I could maybe forgive them based on when the document was written.

I've always wondered about fixing the spec, but it's been that way for >20 years and wouldn't really change anything now.

**Comment by Safihre** [comment]
@mnightingale example article-ID is: `0097HW.2A714583000502E630DE1A38F@news.newsleecher.com`, I wasn't able to do a `HEAD` myself.

**Comment by animetosho** [comment]
Header dump of that article:

	Path: not-for-mail
	From: Bismarck <bnwink@hotmail.com>
	User-Agent: Hogwasher/5.24
	Message-ID: <0097HW.2A714583000502E630DE1A38F@news.newsleecher.com>
	Subject: Stackridge The Man In The Bowler Hat 1973 - "103 The Last Plimsoll.flac" yEnc (13/69) [27427K]
	Newsgroups: alt.binaries.sounds.lossless
	Reply-To: Bismarck
	Lines: 3277
	X-Complaints-To: http://www.newsleecher.com/support/
	NNTP-Posting-Date: Wed, 26 Jul 2023 12:15:11 UTC
	Bytes: 426075
	Date: Wed, 26 Jul 2023 07:15:11 -0500
	X-Received-Bytes: 426218
	
	=ybegin part=13 total=69 line=128 size=28084872 name=103 The Last Plimsoll.flac
	=ypart begin=4915201 end=5324800
	
	[yEnc body]
	
	=yend size=409600 part=13 pcrc32=ffffffff13997c4c

Homepage of the mentioned user agent if you want to try it: https://www.asar.com/hogwasher.html  
Or you can try [submitting a support request](https://www.asar.com/request_hw.html).

**Comment by mnightingale** [comment]
Just to add to what @animetosho found, I'd mention the following

- 64 bit representation of CRC32
- yEnc body starts with "/r/n" instead of "=ybegin"
- yend line ends **200D0A**0D0A2E0D0A rather than 0D0A2E0D0A (extra " \r\n" - "0x20\r\n")

**Comment by animetosho** [comment]
Nice finds!

The start of the yEnc body looks fine to me?

![dump](https://github.com/sabnzbd/sabctools/assets/12937885/edab8597-25c5-4684-8eb3-35a378699f7f)

The end is a bit weird, though presumably acceptable for yEnc.

Looking at the code, I see what the problem is - the CRC32 is sign extended to 64-bit *before* the bit flip, where the bit flip is only performed on the bottom 32 bits, leaving the top 32 bits as all 1s.

![disasm](https://github.com/sabnzbd/sabctools/assets/12937885/5dba5203-4d3e-4c6d-b0ba-d83c2ffa6748)

(side observation: the fact that the size and part number are also sign extended, suggests that this client would have trouble with files over 2GB or more than 32767 parts)

**Comment by mnightingale** [comment]
Strange, not sure what happened there; I'm just seeing "\r\n\r\n" as expected now.

The yend space isn't too important but I can see it breaking could break other clients if they are not handling the possibility of another key/value after crc32.

**Comment by Safihre** [comment]
So what can we do about it, without allowing too much non-standard stuff?
Still @mnightingale's patch?

**Comment by sanderjo** [comment]
I would say both.

- The patch in SAB to solve it now. The posts based on Hogwasher/5.24 will be there until retention ends (10 years from now)
- Report a bug to Hogwasher/5.24 maker ... and see what happens ...

**Comment by Safihre** [comment]
Sounds good. Could you submit a PR? :)

**Comment by mnightingale** [comment]
Sure I'll take a look this evening

**Comment by sanderjo** [comment]
I've filed a bug report with Asar / Hogwash. Webpage says:

```
We have received your request.
We will review your submission and contact you via email if your submission type was “Need Assistance”. If this was a bug or crash report, we will investigate the problem and contact you if further clarification is needed.
```

And now we wait ...
